### ISSUE TITLE
zombie process

### ISSUE THREAD

**Issue by javitorl** [ar-/incron#22]
Every time a program is executed due to an event , a zombie process is left in the system. I think it is quite easy to fix by adding something like:

int status;
waitpid(pid, &status, 0);

in the parent section of the fork at usertable.cpp

**Comment by ronjouch** [comment]
Confirming just-merged PR #23 / 08d8e7a fixes the problem for me. Thanks! 👍

**Comment by ar-** [comment]
fixed
