### ISSUE TITLE
Fix in checkout 08d8e7a26143fa is not a good idea ...

### ISSUE THREAD

**Issue by ericjunkermann** [ar-/incron#40]
... since it results in waiting for each child to finish immediately after it has started. This is likely to mean blocking and not processing any new events if the child happens to be long-running.

I was using 0.5.12 (before that checkout anyway) and getting lots of zombies, so I tried

```
icd-main.cpp
    case SIGCHLD:
+      while (waitpid((pid_t)(-1), 0, WNOHANG) > 0) {}
```

which has resulted in no more zombies.

**Comment by ar-** [comment]
fixed
