### ISSUE TITLE
Recursive directory watching

### ISSUE THREAD

**Issue by ar-** [ar-/incron#8]
Watching a directory recursively is not nativlely supported by inotify and so it is not in incron. Even though is is hightly requested, and actually not too complicated to implement.

A possible python extension is here: https://github.com/nguyent/incron-recursive .

In 2013 the Author tried to get funding to implement this feature, whcih brought him 0 cents. That's one of the reasons why he abondenned the project.

Another alternative seems to be https://github.com/gregghz/Watcher .

Obeserving directories recursively, must be added to incron.

**Comment by ar-** [comment]
https://www.indiegogo.com/projects/recursive-filesystem-monitoring-for-incron

**Comment by k0lter** [comment]
I fail to see why using find command through a system call is faster than

**Comment by ar-** [comment]
The algorithm in [2] considered only the recursive creation on directories but not their deletion. Prevention race condiditions for all possible cases (also considering multiple users on the filesystem) is a very complex problem. I could not see that the algorithm in [2] solves the problem finally.

I decided for 2 reasons, to call find(), but I'm also aware that this is usually considered to be more like a 'hack' and it should be done in CPP.

1. find offered me to include wildcard selectors like *.JPG
2. find was provable correct, quickly implemented and verifiable, even for people without CPP skills (I considered this feature high on demand - even by myself.

Are there any practical concerns? Eg. is find() not available on some platforms? ARM? SPARC? Not sure about this.

**Comment by k0lter** [comment]
find (the GNU version) is known to work on all architectures supported by Debian: https://www.debian.org/ports/
