### ISSUE TITLE
Different /tmp than usual - why and where?

### ISSUE THREAD

**Issue by mviereck** [ar-/incron#89]
Hello,

I found that incron somehow provides a different `/tmp` in incron scripts than the `/tmp` I see regulary.
Am I right?
Why is that done, and can that be disabled?
Where is `/tmp` within incron scripts?

This caused issues in https://github.com/mviereck/x11docker/issues/393

**Comment by versable** [comment]
This is due to how `/tmp` is handled today. Usually it is separated through system namespaces and bind mounts. See: https://systemd.io/TEMPORARY_DIRECTORIES/

**Comment by mviereck** [comment]
Thank you for the clarification!
Meanwhile the problem has been solved with another incrontab related tool.

Just out of curiosity: What if one wants to watch files in `/tmp`?

**Comment by eworm-de** [comment]
Just overwrite the setting in unit file. Create `/etc/systemd/system/incrond.service.d/PrivateTmp.conf` with this content:
```
[Service]
PrivateTmp=false
```

**Comment by mviereck** [comment]
Thank you! That is a quite useful hint.
